<?php
echo "<font color= black face='Calibri'>";

echo "<center>";
echo "<h1>";
echo "<B>";
echo "PROFIL DIRI";
echo "<br>";
echo "<br>";


echo "<table width='560' border='0'>";
  echo "<tr>";
    echo "<td width='51'>";
        echo "&nbsp;";
        echo "</td>";
    echo "<td width='227'>";
        echo "Nama Lengkap";
        echo "</td>";
    echo "<td width='8'>";
        echo ":";
        echo "</td>";
    echo "<td width='254'>";
        echo "Ari Gustiansyah";
        echo "</td>";
  echo "</tr>";

  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
    echo "<td>";
        echo "Nama Panggilan";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "Ari";
        echo "</td>";
  echo "</tr>";
  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
      
    echo "<td>";
        echo "Tempat, Tanggal Lahir";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "Subang, 05 April 2002";
        echo "</td>";
  echo "</tr>";

  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
    echo "<td>";
        echo "Asal Instansi";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "Universitas Mandiri";
        echo "</td>";
  echo "</tr>";
  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
      
    echo "<td>";
        echo "Alamat";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "Cipeundeuy";
        echo "</td>";
  echo "</tr>";
  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
      
    echo "<td>";
        echo "Tinggi/ Berat";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "164/70";
        echo "</td>";
  echo "</tr>";
  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
      
    echo "<td>";
        echo "Cita-cita";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "Menjadi programmer di Tokopedi, Shopee dan StarUp lainnya";
        echo "</td>";
  echo "</tr>";
  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
    echo "<td>";
        echo "Agama";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "Islam";
        echo "</td>";
  echo "</tr>";

  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
    echo "<td>";
        echo "Hobi";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "Bermain Sepak Bola";
        echo "</td>";
  echo "</tr>";
echo "</table>";
?>